version: '3'

services:
  web:
    build: .
    command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    container_name: Blog_website_doc1
    volumes:
      - .:/Blog_website_doc1
    ports:
      - "8000:8000"