# Generated by Django 4.2.4 on 2023-08-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost2',
            old_name='content',
            new_name='content2',
        ),
    ]
