# Generated by Django 4.2.4 on 2023-08-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_rename_titel2_blogpost2_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost2',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
