# Generated by Django 4.2.4 on 2023-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_login_alter_blogpost2_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.SlugField(unique=True),
        ),
    ]
