# Generated by Django 4.2.4 on 2023-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0006_alter_login_email_alter_login_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost2',
            name='title2',
            field=models.CharField(max_length=120),
        ),
    ]
