# Generated by Django 4.2.4 on 2023-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0008_blogpost2_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost2',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost2',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost2',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
