# Generated by Django 4.2.4 on 2023-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0009_blogpost2_publish_date_blogpost2_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost2',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
