# Generated by Django 4.2.4 on 2023-08-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0010_alter_blogpost2_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost2',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
