# Generated by Django 4.2.4 on 2023-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0011_alter_blogpost2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost2',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
