# Generated by Django 4.2.4 on 2023-08-26 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0013_alter_blogpost2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost2',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
