# Generated by Django 4.2.5 on 2024-01-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0015_remove_blogpost2_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost2',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost2',
            name='title2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost2',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
