# Generated by Django 4.2.5 on 2024-01-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0016_alter_blogpost2_timestamp_alter_blogpost2_title2_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog2.blogpost2'),
        ),
        migrations.AlterField(
            model_name='commentsection',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='commentsection',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
