# Generated by Django 4.2.4 on 2023-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentsection_email_commentsection_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
