# Generated by Django 4.2.5 on 2024-01-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentsection_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
