# Generated by Django 4.2.4 on 2023-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
