# Generated by Django 4.2.4 on 2023-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_commentsection_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
