# Generated by Django 4.2.5 on 2024-01-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_commentsection_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.commentsection'),
        ),
    ]
