# Generated by Django 4.2.4 on 2023-08-26 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_commentsection_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
