# Generated by Django 4.2.5 on 2024-02-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentsection_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsection',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.RemoveField(
            model_name='commentsection',
            name='title',
        ),
    ]
