# Generated by Django 4.2.4 on 2023-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_commentsection_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
