# Generated by Django 4.2.5 on 2024-02-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_commentsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentsection'),
        ),
    ]
