# Generated by Django 4.2.5 on 2024-01-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0016_alter_blogpost2_timestamp_alter_blogpost2_title2_and_more'),
        ('comments', '0007_commentsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog2.blogpost2'),
        ),
    ]
