# Generated by Django 4.2.5 on 2024-01-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_remove_commentsection_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsection',
            name='time_stamp',
        ),
    ]
